version: "3.7"
services:
  smeagol-galore:
    image: ${IMAGE}
    container_name: smeagol-galore
    security_opt:
      - no-new-privileges
    networks:
      smeagol_galore:
        ipv4_address: 172.1.2.2
    environment:
      - FQDN=localhost:8443
      # Session timeouts: 60 days in sec = 518400; 30 days = 259200;
      # Maximum session timeout - TGT will expire in maxTimeToLiveInSeconds regardless of usage
      - TGT_MAXTIMETOLIVEINSECONDS=5184000
      # Will expire sooner than maxTimeToLiveInSeconds if no further requests
      - TGT_TIMETOKILLINSECONDS=259200
      # Timeout Smeagol
      - SERVER_SESSION_TIMEOUT=2592000
      # SCMMv2's access token expiration seems to be hard coded to 1h.
      
      # Avoid applications writing to read-only home folder. E.g. jgit (part of SCMM)
      # See https://git.eclipse.org/c/jgit/jgit.git/commit/?id=838b5a84b5093c335b95a644b8888006d9e95493
      - XDG_CONFIG_HOME=/home/tomcat/.scm/
    ports:
      - 8443:8443
      # If SCMM SSH is used
      - 2222:2222
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    volumes:
      - smeagol-galore:/home/tomcat/.scm
      - type: bind
        source: ./config/users.txt
        target: /etc/cas/users.txt
        read_only: true
      - type: bind
        source: ./config/attributes.xml
        target: /etc/cas/attributes.xml
        read_only: true
      - type: bind
        source: ./config/plugin-config.json
        target: /etc/scm/plugin-config.json
        read_only: true
      - type: bind
        source: ./config/certs/localhost
        target: /config/certs/localhost
        read_only: true
      - type: bind
        source: ./config/certs/localhost/cacerts
        target: /opt/java/openjdk/lib/security/cacerts
        read_only: true
      # Examples for more verbose log output
      - type: bind
        source: ./config/scm-logback.xml
        target: /tomcat/webapps/scm/WEB-INF/classes/logback.xml
        read_only: true
      - type: bind
        source: ./config/smeagol-logback.xml
        target: /tomcat/webapps/smeagol/WEB-INF/classes/logback.xml
        read_only: true
      - type: bind
        source: ./config/cas-log4j.xml
        target: /tomcat/webapps/cas/WEB-INF/classes/log4j.xml
        read_only: true
      # Make writable - needed when by tomcat when 'read_only: true'
      - type: tmpfs
        target: /tomcat/work
      - type: tmpfs
        target: /tmp

networks:
  smeagol_galore:
    ipam:
      config:
        - subnet: 172.1.2.0/24

volumes:
  smeagol-galore:
