name: Test scripts on push
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Build image from source and use it for tests, instead of the one from DockerHub
          docker build --no-cache -t smeagol-galore .
          echo 'IMAGE=smeagol-galore' > example/.env
          cd example && docker-compose -f docker-compose-general.yaml up -d
          # Wait for smeagol-galore to startup
          sleep 60 && echo "Finish sleeping"
          # Do some basic sanity checks with the container
          ../test.sh

# TODO run tests on other examples as well (using BATS?)
# do the same for basic setup (Faster without plugin installs) 
# do the same for internal network example
# do the same for internal network example with hostname  - echo '172.1.2.2   smeagol' > /etc/hosts
#  do the same with binding to port 443